name: Build zipfile

on:
  push:
    branches:
      - '*'
  release:
    types: [created]

jobs:
  build-gerber-file:
    runs-on: ubuntu-latest
    container:
      image: setsoft/kicad_auto:ki6
    env:
      gerber_dir: 'dist'
      gerber_zip_file: thin-key-${{ github.sha }}.zip
      schema: 'thin-key.kicad_sch'
      board: 'thin-key.kicad_pcb'
    steps:
    - uses: actions/checkout@v2

    - name: Export gerber
      run: |
        kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.gerber_dir}} \
        -s run_erc,run_drc -v gerbers.gbr drills.gbr drills.drl

    - name: Upload gerber files as artifact
      if: ${{ ! contains(github.ref, 'refs/tags/v') }}
      uses: actions/upload-artifact@v2
      with:
        name: thin-key-${{ github.sha }}
        path: ${{ env.gerber_dir }}

    - name: Archive gerber files
      if: ${{ contains(github.ref, 'refs/tags/v') }}
      run: apt-get update && apt-get install zip;zip -r --junk-paths ${{ env.gerber_zip_file }} ${{ env.gerber_dir }}

    - name: Release to GitHub
      if: ${{ contains(github.ref, 'refs/tags/v') }}
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.gerber_zip_file }}
        draft: true
